services: mongodb

language: go

go:
  - 1.6

script:
  - export GOPATH=`pwd`
  - export PATH=$PATH:$GOPATH/bin
  - export DB_URL=mongodb://localhost/test
  - echo $PATH
  - make fix
  - make localTest
