version: '2'
services:
  app:
    build:
      context: ../build
      dockerfile: tools/Dockerfile
    depends_on:
      - redis
      - mongodb
  redis:
    image: redis
  mongodb:
    image: mongo
