version: '2'
services:
  web:
    build:
      context: ../build
      dockerfile: tools/Dockerfile
    depends_on:
      - redis
      - mongodb
    links:
      - redis:rdb
      - mongodb:db
    environment:
      - DB_URL=mongodb://db:27017/cast
      - REDIS_URL=redis://rdb:6379
      - API_PORT=80
    ports:
      - "12100:80"
    command: server
  worker:
    build:
      context: ../build
      dockerfile: tools/Dockerfile
    depends_on:
      - web
      - redis
    links:
      - web
      - redis:rdb
    environment:
      - API_URL=http://web:80
      - REDIS_URL=redis://rdb:6379
    command: worker
  redis:
    image: redis
    ports:
      - "12101:6379"
  mongodb:
    image: mongo
    ports:
      - "12102:27017"
