version: '2'
volumes:
  # Used by webwatch. it writes the webpack bundle here
  dashboard: {}
  # node_modules is overlayed on top of the users share
  node_modules: {}
services:
  web:
    build:
      context: ../build
      dockerfile: tools/Dockerfile.dev
    depends_on:
      - redis
      - mongodb
    links:
      - redis:rdb
      - mongodb:db
    environment:
      - DB_URL=mongodb://db:27017/cast
      - REDIS_URL=redis://rdb:6379
      - API_URL=http://web:80
    ports:
      - "12100:80"
    command: sh -c 'make server && server'
    volumes:
      - dashboard:/app/dashboard/dist
  worker:
    build:
      context: ../build
      dockerfile: tools/Dockerfile.dev
    depends_on:
      - web
      - redis
      - mongodb
    links:
      - web
      - redis:rdb
      - mongodb:db
    environment:
      - DB_URL=mongodb://db:27017/cast
      - API_URL=http://web:80
      - REDIS_URL=redis://rdb:6379
    command: sh -c 'make worker && worker -q update-feed -q update-user-feeds'
  redis:
    image: redis
    ports:
      - "12101:6379"
  mongodb:
    image: mongo
    ports:
      - "12102:27017"
  watcher:
    build:
      context: .
      dockerfile: Dockerfile.watcher
    depends_on:
      - web
    volumes:
      - ../dashboard:/app
      - dashboard:/app/dist
      - node_modules:/app/node_modules
    command: webpack --watch --watch-poll
